{% set version = "2.0.3.0" %}
{% set sha256 = "b296c6e1f04790cd3c8594a9b86f5d25346266413e0b363b6b4bdc7f75cc7a47" %}

package:
  name: maxquant
  version: '{{ version }}'

source:
  # link from https://drive.google.com/drive/folders/1Ja9iaCQ6mM66VQEeaS36hqq77bnsmxQF
  url: https://drive.google.com/file/d/16nk1o__B5Vo1lbKx8_BNfnm1QnDpRPvL/view?usp=drive_link
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 2

  script:

    - cp -r * $PREFIX
    - cp $RECIPE_DIR/maxquant $PREFIX/bin/maxquant
    - chmod +x $PREFIX/bin/maxquant
    - chmod +x $PREFIX/bin/MaxQuantCmd.exe
    - chmod +x $PREFIX/bin/MaxQuantGui.exe
    - chmod +x $RECIPE_DIR/xmlcombine.py
    - $RECIPE_DIR/xmlcombine.py $PREFIX/bin/conf/modifications.xml $RECIPE_DIR/mod_*.xml > $PREFIX/bin/conf/modifications_temp.xml
    - mv $PREFIX/bin/conf/modifications_temp.xml $PREFIX/bin/conf/modifications.xml

requirements:
  host:
    - python >=3.6
  run:
    - dotnet-runtime >=3.1

test:
  commands:
    - maxquant --version 2>&1 > /dev/null | grep {{ version }}

about:
  home: http://www.coxdocs.org/doku.php?id=maxquant:start
  license: http://www.coxdocs.org/lib/exe/fetch.php?media=license_agreement.pdf
  summary: MaxQuant is a quantitative proteomics software package designed for analyzing large mass-spectrometric data sets. License restricted.

extra:
  identifiers:
    - biotools:MaxQuant
    - biotools:maxquant
    - doi:10.1038/s41592-018-0018-y
    - usegalaxy-eu:maxquant
