{% set CONDA_BOOST = "1.66" %}
package:
  name: cfm-id
  version: "33"

source:
  # the download is a mirror of a snapshot of 
  # https://sourceforge.net/code-snapshots/svn/c/cf/cfm-id/code/cfm-id-code-r33-cfm.zip
  # which is only present for 24h or so
  url: https://depot.galaxyproject.org/software/cfm/cfm_r33_src_all.zip
  md5: f02c79016eae6ad95413213509513eed
  patches:
    - CMakeLists.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost
    - lp_solve
    - rdkit ==2018.09.1
  run:
    - boost
    - lp_solve
    - rdkit ==2018.09.1

# files taken from https://sourceforge.net/p/cfm-id/code/HEAD/tree/supplementary_material/cfm-train_example/train_example/
test:
  source_files:
    - example_candidates.txt
    - example_spec.txt
  files:
    - param_output.log
    - param_config.txt
  commands:
    - cfm-id example_spec.txt AN_ID example_candidates.txt 5 10.0 0.01 0.001 param_output.log param_config.txt DotProduct
about:
  home: https://sourceforge.net/p/cfm-id/wiki/Home/
  license: GPL-2
  summary: 'Tools for applying Competitive Fragmentation Modeling (CFM) to spectrum prediction and metabolite identification tasks, as well as a tools for fragment generation and peak annotation.'
  license_file: license.txt
