{% set name = "rgcca" %}
{% set version = "3.0.0" %}

package:
  name: {{ name }}cmd
  version: {{ version }}

source:
  url: https://github.com/rgcca-factory/{{ name|upper }}/archive/{{ version }}.tar.gz
  sha256: e88f9554fd5618e02a4eb3b88c01e4352d14ea61d837255ece53f5b9a2d2bb17 

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/
    - lib/R/lib/

requirements:
  host:
    - r-base
    - r-gridextra
    - r-deriv
    - r-mass
    - r-ggplot2
    - r-optparse
    - r-scales
    - r-igraph
    - r-ggrepel
    - r-openxlsx
    - r-rlang
    - r-vegan
    - r-pbapply
    - r-plotly
  run:
    - r-base
    - r-gridextra
    - r-deriv
    - r-mass
    - r-ggplot2
    - r-optparse
    - r-scales
    - r-igraph
    - r-ggrepel
    - r-openxlsx
    - r-rlang
    - r-vegan
    - r-pbapply
    - r-plotly
test:
  commands:
    - cd ${PREFIX} && ls && Rscript inst/launcher.R -h
    - rgcca -h
    - $R -e "library('RGCCA')"

about:
  home: https://CRAN.R-project.org/package=RGCCA
  doc_url: https://github.com/ecamenen/rgcca-conda/blob/master/README.md
  license: GPL (>= 2)
  license_family: GPL3
  summary: 'Multiblock data analysis concerns the analysis of several sets of variables
        (blocks) observed on the same group of individuals. The main aims of the RGCCA
        package are (i) to study the relationships between blocks and (ii) to identify
        subsets of variables of each block which are active in their relationships
        with the other blocks.'

extra:
  recipe-maintainers:
    - ecamenen
