{% set version="2.59" %}
{% set hash="a551706f810f6daf702fd90318dda08bb69e1feb0f8431bf5cbc87c6a1b8cdde" %}
package:
  name: stacks
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]

source:
  sha256: {{ hash }}
  url: http://catchenlab.life.illinois.edu/stacks/source/stacks-{{ version }}.tar.gz
  patches:
    - at.patch
    - kmer_exit.patch

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib
    - openmp  # [linux]
  run:
    - perl
    - perl-bioperl-core
    - perl-file-spec
    - perl-file-temp
    - perl-posix
    - python >=3
    - velvet
    - samtools
    - zlib
    - openmp  # [linux]

test:
  commands:
    - command -v cstacks
    - command -v gstacks
    - command -v sstacks
    - command -v ustacks
    - command -v phasedstacks
    - command -v populations
    - command -v process_radtags
    - command -v process_shortreads
    - command -v clone_filter
    - command -v kmer_filter
    - command -v stacks-dist-extract
    - command -v stacks-integrate-alignments
    - command -v tsv2bam
    - command -v convert_stacks.pl
    - command -v count_fixed_catalog_snps.py
    - command -v denovo_map.pl
    - command -v extract_interpop_chars.pl
    - command -v integrate_alignments.py
    - command -v ref_map.pl

about:
  home: http://catchenlab.life.illinois.edu/stacks/
  license: GPL
  license_file: LICENSE
  summary: Stacks is a software pipeline for building loci from RAD-seq

extra:
  identifiers:
    - biotools:Stacks
    - doi:10.1111/mec.12354
