{% set name = "argparse2tool" %}
{% set version = "0.4.8" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 749de9a1278e6c2795993a0d12e99492b7cf4e52d7862c9ef211f9ff17d8c52e

build:
  number: 0
  entry_points:
    - argparse2tool_check_path = argparse2tool.check_path:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - future
    - galaxyxml >=0.2.3
    - jinja2
    - python

test:
  imports:
    - argparse2tool
    - argparse2tool.cmdline2cwl
    - argparse2tool.cmdline2gxml
  commands:
    - argparse2tool_check_path --help

about:
  home: "https://github.com/erasche/argparse2tool"
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.TXT
  summary: "Instrument for forming Galaxy XML and CWL tool descriptions from argparse arguments"
  doc_url: "https://github.com/erasche/argparse2tool"
  dev_url: "https://github.com/erasche/argparse2tool"

extra:
  recipe-maintainers:
    - bernt-matthias 
