{% set name = "mitos" %}
{% set version = "1.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3
  run:
    - biopython <1.68
    # - ete2 ==2.3*
    - python >=3
    # - reportlab
    - blast-legacy =2.2
    - infernal =1.0
    - viennarna <2
    - r-base >=3 
    - r-ggplot2
    - openjdk >8

test:
  imports:
    - mitos
    - mitos.bedfile
    - mitos.blast
    - mitos.codon
    # - mitos.draw
    - mitos.extprog
    - mitos.feature
    - mitos.gb
    - mitos.gfffile
    - mitos.mergefeature
    - mitos.mitfi
    - mitos.mito
    - mitos.mitofile
    - mitos.msa
    - mitos.rEvoluzer
    - mitos.rna
    - mitos.sequence
    - mitos.tax
    - mitos.tbl
    - mitos.trna
    - mitos.update
    - mitos.webserver
  commands:
    - runmitos.py -h

about:
  home: http://mitos.bioinf.uni-leipzig.de
  license: MIT
  license_family: MIT
  license_file: LICENSE 
  summary: MITOS is a tool for the annotation of metazoan mitochondrial genomes.
  dev_url: https://gitlab.com/Bernt/MITOS 

extra:
  recipe-maintainers:
    - bernt-matthias
    
