package:
  name: group_humann2_uniref_abundances_to_go
  version: '1.3.0'

source:
  md5: a78d947cfff8e76297840dd6ce8bfe7f
  url: https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO/archive/v1.3.0.zip
  patches:
    # xref https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO/issues/12#issuecomment-2613954247
    - url.patch

build:
  number: 2
  noarch: generic
  run_exports:
    - {{ pin_subpackage("group_humann2_uniref_abundances_to_go", max_pin="x.x") }}


requirements:
  run:
    - python <3
    - humann2
    - goatools =0.6.10
    - wget

test:
  commands:
    - group_humann2_uniref_abundances_to_GO.sh -h

about:
  home: 'https://github.com/ASaiM/group_humann2_uniref_abundances_to_GO'
  summary: "Group abundances of UniRef50 gene families obtained with HUMAnN2 to Gene Ontology (GO) slim terms with relative abundances"
  license: "Apache 2"
