{% set version = "6.1" %}
{% set sha256 = "4b88aaad8f953b1b50bc7d06f3a5920f0d589d2c9a26c709199f8347905f5867" %}

package:
  name: ncbi-util-legacy
  version: {{ version }}

source:
  # TODO url might not be stable
  url: ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools/ncbi.tar.gz
  sha256: {{ sha256 }}
  folder: ncbi
build:
  number: 6

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - gnutls
    - tcsh
  run:

# test:
#   files:
#     - test.fa
#     - testdatabase.fa
#   commands:
#     # (see run_tests.sh for remainder of tests)
#     - blastn -help
#     - blastp -help
#     - makeblastdb -help
#     # test that BLAST ignores LD_LIBRARY_PATH
#     - touch libstdc++.so.6; LD_LIBRARY_PATH=. makeblastdb -help && rm libstdc++.so.6
#     # - update_blastdb.pl --help (disabled as it now starts a pager, stalling forever)

about:
  home: http://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastDocs
  license: Public Domain
  summary: BLAST+ is a new suite of BLAST tools that utilizes the NCBI C++ Toolkit.

extra:
  identifiers:
    - biotools:blast
    - doi:10.1016/S0022-2836(05)80360-2
