{% set version = "3.5.0" %}

package:
  name: mzmine
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  - url: https://github.com/robinschmid/mzmine3/archive/refs/heads/jdk20.zip
    sha256: ace4189a75a3d8d603541aa8673fd6f05ccac51053ccb2d0323758a1497bd9e6

requirements:
  build:
    - openjdk =20
  run:
    - openjdk =20
    - pango  # /home/conda/.openjfx/cache/16/libjavafx_font_pango.so: libpangoft2-1.0.so.0: cannot open shared object file

test:
  commands:
    # MZmine has no --help flag, but still prints help containing version number
    # MZmine 3.2.8 prints version nubmer 3.2.9 
    - MZmine --help
    - (MZmine --help || true) |& grep "Starting MZmine {{ version }}"

about:
  home: http://mzmine.github.io/
  license: MIT
  summary: Integrative analysis of multimodal mass spectrometry data
  description: |
    MZmine 3 is an open-source and platform-independent software for mass
    spectrometry (MS) data processing and visualization. It enables large-scale
    metabolomics and lipidomics research by spectral preprocessing, feature
    detection, and various options for compound identification, including
    spectral library querying and creation.
