{% set name = "iqtree" %}
{% set version = "2.2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version | replace("-", "_") }}

build:
  number: 0

source:
  - url: https://github.com/iqtree/iqtree2/archive/v{{ version }}.tar.gz
    sha256: 7640a730bae81b56ffff5bcc03a20e6d63962fdde893ea4887cdd6c79076180b
    #patches:
    #  - 0001-PATCH-macos-10.9.patch
  - url: https://github.com/tothuhien/lsd2/archive/v1.9.9.tar.gz
    sha256: decda612ad7f26c67d50f3dc46fb14bfc2ac90776e460b14c548fd6f9d281454
    folder: lsd2

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - llvm-openmp  # [osx]
    - ld64 # [osx]
  host:
    - boost-cpp
    - eigen
    - zlib

test:
  commands:
    - iqtree
    - iqtree2

about:
  home: "http://www.iqtree.org/"
  dev_url: https://github.com/iqtree/iqtree2
  license: GPL-2.0-or-later
  summary: "Efficient phylogenomic software by maximum likelihood."

extra:
  identifiers:
    - biotools:iq-tree
    - doi:10.1093/molbev/msu300
    - usegalaxy-eu:{{ name|lower }}
