{% set version = "20.9.0" %}
{% set sha256 = "904ec4a02e3cd572ae898ad4b37d2eff5cb1fb99dc70fa96aaddc31dd5ad578b" %}

package:
  name: galaxy-objectstore
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/09/5b/26662352bddaf874997fae4014218548bd4eb847eb86f9a0f9a61ffd9f4b/galaxy-objectstore-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - galaxy-util
    - pyyaml
    - python >=3.5
    - six >=1.9.0

test:
  imports:
    - galaxy
    - galaxy.objectstore
    - galaxy.objectstore.cloud

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: The Galaxy object store framework and default implementations
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  identifiers:
    - biotools:galaxy
    - doi:10.1093/nar/gky379
  recipe-maintainers:
    - bernt-matthias
