{% set version = "2.2" %}
{% set sha256 = "5fd4aca1263dedb9704f2d1fb05e969d6160b53469f502ba27389c94d40e1b95" %}

package:
  name: metaxa
  version: {{ version }}

source:
  url: http://microbiology.se/sw/Metaxa2_{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  run:
    - perl
    - hmmer>=3.1b
    - blast>=2.2
    - mafft>=7
    - usearch>=7
test:
#   files:
#     - test.fa
#     - testdatabase.fa
  commands:
    - metaxa2 --help
#     # (see run_tests.sh for remainder of tests)
#     - blastp -help
#     - makeblastdb -help
#     # test that BLAST ignores LD_LIBRARY_PATH
#     - touch libstdc++.so.6; LD_LIBRARY_PATH=. makeblastdb -help && rm libstdc++.so.6
#     # - update_blastdb.pl --help (disabled as it now starts a pager, stalling forever)

about:
  home: http://microbiology.se/software/metaxa2/
  license: GPL3
  summary: Improved Identification and Taxonomic Classification of Small and Large Subunit rRNA in Metagenomic Data.

extra:
  identifiers:
    - biotools:metaxa
    - doi:10.1111/1755-0998.12399
    - doi:10.1093/bioinformatics/bty482
