{% set name = "revoluzer" %}
{% set version = "0.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://gitlab.com/Bernt/{{ name }}/-/archive/0.1/{{ name }}-{{ version }}.tar.gz
  sha256: 1904caf6779fe9c726649d28da093990ea64d24910fa5ed5ebdf1c85bde43f34

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - crex

about:
  home: https://gitlab.com/Bernt/revoluzer/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Genome rearrangement analysis tools

extra:
  recipe-maintainers:
    - bernt-matthias
