{% set name = "revoluzer" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://gitlab.com/Bernt/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6df3d0b41a4d916bf6082a77b9c110197851cc2e

build:
  number: 0
  skip: True  # [osx]
  run_exports:
    - {{ pin_subpackage('revoluzer', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - boost-cpp
    - glpk
  host:
  run:
    - boost-cpp
    - glpk

test:
  commands:
    - crex --help
    - trex -h

about:
  home: https://gitlab.com/Bernt/revoluzer/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Genome rearrangement analysis tools

extra:
  recipe-maintainers:
    - bernt-matthias
