{% set name = "revoluzer" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://gitlab.com/Bernt/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b75580a4a596b77ee3a73952585660d61f8aaaa9965fa73e36197a2bbefa9b83

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('revoluzer', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - boost-cpp
    - glpk
  host:
  run:
    - boost-cpp
    - glpk

test:
  commands:
    - crex

about:
  home: https://gitlab.com/Bernt/revoluzer/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Genome rearrangement analysis tools

extra:
  recipe-maintainers:
    - bernt-matthias
