{% set name = "revoluzer" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://gitlab.com/Bernt/{{ name }}/-/archive/0.1/{{ name }}-{{ version }}.tar.gz
  sha256: 7b153d726733412ed7e15423ea9fd24835f318b316d59a249d72316d5d7ae0ce

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('revoluzer', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
  run:

test:
  commands:
    - crex

about:
  home: https://gitlab.com/Bernt/revoluzer/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Genome rearrangement analysis tools

extra:
  recipe-maintainers:
    - bernt-matthias
