{% set version = "23.0.3" %}
{% set sha256 = "a7441199a7748d02ead451d92454006bbefb0b01c90db516a433d1024f1fdce8" %}
{% set galaxy_version = version.split(".")[:2]|join(".") %}

package:
  name: galaxy-files
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/galaxy-data/galaxy-files-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - galaxy-util >={{ galaxy_version }}
    - fs
    - typing-extensions
    - python >=3.7

test:
  imports:
    - galaxy
    - galaxy.files

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: The Galaxy file sources framework and default plugins.
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  identifiers:
    - biotools:galaxy
    - doi:10.1093/nar/gky379
  recipe-maintainers:
    - bernt-matthias
