{% set name = "megan" %}
{% set version = "6.12.3" %}
{% set sha256hash = "a9062c33692eac51db135161d04163d412a0ec83cb94ada40f7f912186fc7529" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ab.inf.uni-tuebingen.de/data/software/megan6/download/MEGAN_Community_unix_6_12_3.sh
  sha256: {{ sha256hash }}

build:
#  detect_binary_files_with_prefix: true
  number: 0

requirements:
  run:
    # Enforce a version requirement on openjdk to ensure
    # it comes from the conda-forge channel and not default.
    # Many yaks were shaved to bring us this information.
    # Version number reference: https://github.com/conda/conda/issues/6948#issuecomment-369360906
    - openjdk >=8.0.144

test:
  commands:
    - aadder-run -h
    - aadder-build -h
    - blast2lca -h
    - blast2rma -h
    - daa2info -h
    - daa2rma -h
    - daa-meganizer -h
    - extract-biome -h
    - gc-assembler -h
    - maf2daa -h
    - rma2info -h
    - sam2rma -h
    - sort-last-maf -h
    - references-annotator -h
#    - MEGAN -h

about:
  home: 'http://ab.inf.uni-tuebingen.de/software/megan6/'
  license: GPL >=3
  summary: 'A tool for studying the taxonomic content of a set of DNA reads'

extra:
  identifiers:
    - biotools:megan
