{% set version = "1.1.2" %}

package:
  name: figaro
  version: {{ version }}

source:
  url: https://github.com/Zymo-Research/figaro/archive/refs/tags/{{ version }}.tar.gz
  sha256: b80d8258574ae9c6ba402e8e8de5eebb1fa1f71a3d81c1cc2d9c0f6729b9a3ec

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  noarch: python

requirements:
  build:
    - pip
    - python >=3.8
    - sed
  run:
    - numpy >=1.13.1
    - scipy >=1.2.1
    - matplotlib-base >=3.0.2
    - python >=3.8

test:
  commands:
    - figaro.py -h
  import:
    - figaroSupport

about:
  home: https://github.com/Zymo-Research/figaro
  summary: An efficient and objective tool for optimizing microbiome rRNA gene trimming parameters
  license: GPLv3
  license_file: LICENSE
 
