{% set version = "1.0.3" %}
{% set sha256 = "60706dff99daf8e3e42348f037a32bdc7e62e88f6a3ccbd10aee0fe8cd183116" %}

package:
  name: dashing
  version: {{ version }}

build:
  skip: True  # [osx]
  number: 0

source:
  git_url: https://github.com/dnbaker/dashing
  git_rev: v{{ version }}
  sha256: {{sha256}}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - zstd
    - make
  host:
    - zlib
  run:
    - zlib

test:
  commands:
    - dashing --help 2>&1 | grep {{ version }}

about:
  home: https://github.com/dnbaker/dashing
  license: GPL-3
  summary: Fast and accurate genomic distances using HyperLogLog
  license_file: LICENSE

extra:
  identifiers:
    - doi:10.1101/501726
  recipe-maintainers:
    - silask
    - dnbaker
  skip-lints:
    - uses_vcs_url
